// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { langserveBlock } from '.'

export const langserveBlockSchema = parseBlockSchema(langserveBlock)
export const langserveCredentialsSchema = parseBlockCredentials(langserveBlock)
